add parsing, processing comments
EV-charges/parsers pull request #14
Opened 2023-06-22 12:39 UTC by Ruby821

Здесь всё, кроме функции, которая будет получать AccessToken с сайта, т.к. комменты забирать могут только авторизованные пользователи. 
Сделал функцию extracts_dicts, т.к. в зависимости от количества комменты одного места могут приходить нам как в одном списке, так и в нескольких.
В некоторых местах помоему код слишком сдвинулся вправо, но как сделать по другому я не придумал

2023-06-27 20:32 UTC, MarkAntipin requested changes

2023-06-27 20:32 UTC, MarkAntipin commented on settings.py
> +    def get_or_post_places(self) -> str:
places_url?

2023-06-27 20:32 UTC, MarkAntipin commented on settings.py
> +    def post_comments(self) -> str:
comments_url?

2023-06-27 20:32 UTC, MarkAntipin commented on src/electromaps/run.py
> +#from src.utils.make_request_proxy import make_request_proxy
это почему убрал?

2023-06-27 20:32 UTC, MarkAntipin commented on src/electromaps/run.py
> +    #response = make_request_proxy(url=settings.PLACES_URL + coordinates, retries_proxy=15, method=RequestMethod.GET)
почему убрал?

2023-06-27 20:32 UTC, MarkAntipin commented on src/electromaps/run.py
> +            resp = make_request(
надо через прокси делать запросы туда, чтобы нас не забанили

2023-06-27 20:32 UTC, MarkAntipin commented on src/electromaps/run.py
> +            resp = make_request(
Если забанят тачку, то придется покупать новую, у нее статический ip

2023-06-27 21:34 UTC, Ruby821 commented on src/electromaps/run.py
> +            resp = make_request(
По прокси у Димы узнаю задумку и переделаю, просто гит жаловался на эти строки

2023-06-28 19:56 UTC, MarkAntipin approved these changes

2023-06-29 11:46 UTC, merged